---
title: "Hello!"
author:
  - name: Chase M Clark
    orcid: 0000-0001-6439-9397
categories: []
date: "2023-12-30"
description: "Information about how this blog works and general info"
---


A major issue when writing code/computational analyses for science is ensuring the code is reproducible. There's a ton of work that goes on behind the scenes to make code and data FAIR, reproducible, and broadly useful across computational platforms. For now I'll leave all of that undefined and abstract, hopefully in the future we'll have time write about those steps in more detail.

For the puropose of this postI wanted to highlight what we've done to setup this Blog to not only explain how certain computational analyses are performed but to also ensure that each post is able to reproduced by anyone during their learning journey.

1) Each post lives in its own directory.
2) Each post directory contains a Dockerfile which contains all the dependencies necessary to run the scripts in the post. If not, the post will mention/describe what is missing or why Docker couldn't be used. If there is no Dockerfile then it should be assumed the base Dockerfile of the blog was used.
3) The entire Blog is rendered/compiled with [Quarto](https://quarto.org), "An open-source scientific and technical publishing system". This enables us to write posts as Jupyter notebooks (.ipynb files), Quarto documents (.qmd files), Rmarkdown (.rmd files) and likely more. This provides us flexibility to demonstrate different skills all within a single publishing framework.

Though most posts will not be modified there may be cases where we would like to expand/contract/modify/clarify/etc a post. In other words posts shouldn't be considered static, and if our systems are working they should automatically have a modified date alongside the original published date.

If you find a post helpful or would like to add to the discussion there should be a place for you to do so at the bottom of each post, which works through Quarto integration with [giscus](https://github.com/giscus/giscus). We're still new to this (and will see how much moderation it requires) but it basically automates the synchronization of GitHub Discussions with comment sections within each post.